# sentinelops/infrastructure/docker-compose.yml

version: '3.8'

services:
  # Database
  postgres:
    image: postgres:14
    container_name: sentinelops-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sentinelopsdev}
      POSTGRES_USER: ${POSTGRES_USER:-sentinelopsuser}
      POSTGRES_DB: ${POSTGRES_DB:-sentinelops}
    volumes:
      - sentinelops-postgres-data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sentinelopsuser} -d ${POSTGRES_DB:-sentinelops}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Message queue
  kafka:
    image: bitnami/kafka:latest
    container_name: sentinelops-kafka
    restart: always
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - sentinelops-kafka-data:/bitnami/kafka

  # Data processing
  processor:
    build:
      context: ../backend/data-processor
      dockerfile: Dockerfile
    container_name: sentinelops-processor
    restart: always
    depends_on:
      kafka:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-sentinelopsuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sentinelopsdev}
      - POSTGRES_DB=${POSTGRES_DB:-sentinelops}
    volumes:
      - ../backend/data-processor:/app
      - sentinelops-log-data:/var/log/sentinelops

  # API server
  api:
    build:
      context: ../backend/api-server
      dockerfile: Dockerfile
    container_name: sentinelops-api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-sentinelopsuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sentinelopsdev}
      - POSTGRES_DB=${POSTGRES_DB:-sentinelops}
      - ENABLE_PROMETHEUS=true
      - API_PORT=${API_PORT:-8000}
      - JWT_SECRET=${JWT_SECRET:-default_secret_change_me_in_production}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ../backend/api-server:/app
      - sentinelops-log-data:/var/log/sentinelops

  # Metrics & monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: sentinelops-prometheus
    restart: always
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - sentinelops-prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  # Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: sentinelops-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=${API_URL:-http://localhost:8000}

# Named volumes for persistence
volumes:
  sentinelops-postgres-data:
    driver: local
  sentinelops-kafka-data:
    driver: local
  sentinelops-prometheus-data:
    driver: local
  sentinelops-log-data:
    driver: local